import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Nav from "./nav";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* TODO: Not sure if making body a flex is acceptable */}
      <body
        className={`${spaceGrotesk.className} antialiased flex flex-col items-center`}
      >
        <Nav />
        <div className="max-w-screen-lg mt-9 mb-14">{children}</div>
      </body>
    </html>
  );
}
